#!/bin/sh

if [ ! -x /usr/local/bin/cdc3 ]
then
    exit 0
fi

if [ ! -x /var/tmp/cdc3.log ]
then
    touch /var/tmp/cdc3.log
    chmod ga+w /var/tmp/cdc3.log
fi

if [ "$1" = "start" ]
then
    echo "Starting cdc3: "
    /usr/local/bin/cdc3  >> /var/tmp/cdc3.log 2>&1 &
fi
