#!/bin/bash
# 
# Nitro kernel command contains:   console=ttymxc1,115200
#

for arg in $(cat /proc/cmdline)
do
    case $arg in
        console=*)
            tty=${arg#console=}
            tty=${tty#/dev/}
 
            case $tty in
                tty[a-zA-Z]* )
                    PORT=${tty%%,*}
 
                    # check for service which do something on this port
                    if [ -f /etc/init/$PORT.conf ];then continue;fi 
 
                    SPEED=${tty##$PORT,}
                    BITS='8'

                    # 8bit serial is default
                    [ -z $BITS ] && BITS=8
                    [ 8 -eq $BITS ] && GETTY_ARGS="$GETTY_ARGS -8 "
 
                    [ -z $SPEED ] && SPEED='115200,57600,38400,19200,9600'
 
                    GETTY_ARGS="$GETTY_ARGS $SPEED $PORT"
                    #echo "GETTY_ARGS: " $GETTY_ARGS > /xyz.txt
                    exec /sbin/getty $GETTY_ARGS
            esac
    esac
done
